### ISSUE TITLE
bs_seeker2-call_methylation.py line 286 makes bad comparison to pysam version string

### ISSUE THREAD

**Issue by iankorf** [BSSeeker/BSseeker2#13]
On line 286, there is the following statement

`if pysam.__version__ > "0.8.0" :`

The problem is that pysam is on version 0.10.0. Therefore, a simple string comparison no longer works because 0.10.0 is lexically less than 0.8.0 even though in version numbers it's greater.

Instead of using string comparison, use distutils.version.LooseVersion().

**Comment by guoweilong** [comment]
Great thanks, @iankorf !

The fixed code is just commited.

Best,
Weilong

**Comment by hlfernandez** [comment]
Thank you @guoweilong. However, last version of BS-Seeker2 (v2.1.1) still presents this problem in that line and fails in line 289 because of the bad version comparison.

Since I am using pysam v0.11.2.1, I have commented line 286 to ignore the bad _if_ and made the correct assignment (_pr_qpos = pr.query_position_).

Moreover, taking a look at commit "[fix version error](https://github.com/BSSeeker/BSseeker2/commit/548208b3cf6852a54f7f7c9b55806e905d6d48d1)", the problem seems to be fixed on line 132 but line 286 has not been changed.

**Comment by guoweilong** [comment]
@hlfernandez Thanks. I just noticed your message by checking back. Now it should be fixed.

Weilong
